# Store non-sensitive Postgres settings and credentials
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: studentdb
  POSTGRES_USER: postgres
---
# Store sensitive Postgres password separately from the ConfigMap
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres123
